name: Build LaTeX to HTML
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX to HTML
        uses: docker://ghcr.io/michal-h21/make4ht-action:latest
        env:
          command: "make4ht -u -d out main.tex"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
